# Generated by Django 5.1.2 on 2024-12-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecpies', '0006_remove_userprofile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingridents',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=100),
        ),
    ]
